### ISSUE TITLE
Update fastp version for speedup and reproducibility

### ISSUE THREAD

**Issue by Jakob37** [Clinical-Genomics-Lund/nextflow_wgs#143]
The fastp version we are using does not seem to produce fully reproducible results.

According to the docs, v0.23.0 should do so.

Also, when testing, it processed a sample in ~1 minute, versus ~5 for the older version.

The md5sum still differed though, but not the number of characters in the file. So it warrants some further testing.

https://github.com/OpenGene/fastp/releases/tag/v0.23.0

**Comment by alkc** [comment]
Let's try to squeeze this one into the february validation branch

**Comment by Jakob37** [comment]
I'll test run this one!
