### ISSUE TITLE
-resume in nextflow does not work for sentieon_qc for various pipelines

### ISSUE THREAD

**Issue by ViktorHy** [Clinical-Genomics-Lund/nextflow_wgs#17]

**Comment by ViktorHy** [comment]
Might be publishDir that causes this. overwrite: 'true' is default behavior. In -resume the defualt behavior is false. As we set it to true it might always be true. All three processes affected by this has publishDirs set to always true. Although, there are processes where resume works and overwrite is set to always true

**Comment by ViktorHy** [comment]
Above suggestion was not helpful. Consider temporary files created by process. Both sentieon_qc and generate_gens_data create intermediary files which are removed by scripts. Can these cause failure to resume?

**Comment by sima-r** [comment]
Since a copy of previously produced file exists in the cache, probably this is not the reason. I tried it for a process and it resumed as expected.
