### ISSUE TITLE
Load MT frequencies into loqusdb

### ISSUE THREAD

**Issue by Jakob37** [Clinical-Genomics-Lund/nextflow_wgs#173]
We both need to load MT variants into LoqusDB as part of the SNV load. The issue is that the MT caller does not output quality fields compatible with what is expected by LoqusDB.

A primitive solution would be to add quality values directly to all MT variants with a predefined value.

A more sophisticated solution would be to translate existing scores into the expected score format.

We would also need to load previous variants into the production db (@ViktorHy has means to do this).

**Comment by Jakob37** [comment]
Could this one be said to be completed @ViktorHy ?

**Comment by ViktorHy** [comment]
yes, closing
