### ISSUE TITLE
Starting trios from BAM is broken due to sample and group id mixup in bqsr process

### ISSUE THREAD

**Issue by alkc** [Clinical-Genomics-Lund/nextflow_wgs#219]
The input channel content sent to  `bam_choice` and all downstream stuff contains tuples of `[group_id, sample_id, bam_path, bai_path]`.

However, the `bqsr` process unpacks these as:

```
process bqsr { ...
input:                                                                    
    set id, group, file(bam), file(bai) from bam_bqsr.mix(bam_bqsr_choice)
```

Group id and sample id switch place inside the process, which results in `dnascope` not being run for relatives and later on a crash down the line in `split_normalize`. Singles where sample id is the group id will still run fine.

**Comment by Jakob37** [comment]
Duplicate of #137 , the PR will probably fix both
