### ISSUE TITLE
Add mtDNA variants to pipeline

### ISSUE THREAD

**Issue by bjhall** [Clinical-Genomics-Lund/nextflow_wgs#51]
For discussion:

- [ ] Update gnomAD to 3.1 (or atleast add the mtDNA part of gnomAD 3.1)
- [x] Integrate Paul's calling/annotation pipeline into the main pipeline
   - [x] Add mutserve, hmtnote, haplogrep and eklipse to container
   - [x] Add new MT processes
   - [x] Merge MT vcf with other variants after `split_normalize` or `intersect` process
- [x] Add gnomAD annotation for mtDNA
- [x] Add MT variants to loqusDB 
- [x] Modiify rank model for MT variants
  - [x] -12 on >0.5% gnomAD
  - [x] -12 or hard filter variants with VAF < 5%
- [x] Scout modifications (add issue(s) to scout repo)
  - [x] Show MT-gnomAD in variant list
  - [x] Show various annotations in variant detail view
    - [x] Mitomap
    - [x] MT-gnomAD
    - [x] more??
  - [x] Show eklipse image somewhere
  - [x] Show haplogroup image somewhere

Some questions
- How will genmod models handle mtDNA variants?
- What's the sensitivity for SNVs and SVs at low heteroplasy levels. Make insilico titration analysis
- more???

**Comment by ViktorHy** [comment]
how does rank for SVs handle mt-variants?

**Comment by ViktorHy** [comment]
was completed April 2021
