### ISSUE TITLE
calculate mitochondrial coverage for CDM

### ISSUE THREAD

**Issue by ViktorHy** [Clinical-Genomics-Lund/nextflow_wgs#62]
Need to add a process or reuse sentieon QC-process to calculate coverage for MT-DNA

* mean
* % above 500X

Would probably need to be handled as a panel if run through sentieon?

* check whether sentieon already calculates coverage for MT
* check if any MT-specific software calculates coverage for MT
  * hmtnote
  * eclipse
  * mutect2
  * haplotgrep

**Comment by ViktorHy** [comment]
https://github.com/Clinical-Genomics-Lund/cmd-data-management/issues/8

**Comment by alkc** [comment]
Could we use samtools for mitochondrial mean coverage?

Something like: `samtools coverage  "/path/to/results/wgs/bam/some-sample_mito.bam" | grep "^M" | cut -f 7`

**Comment by alkc** [comment]
Can we reuse already existing sentieon commands for calculating the mito coverage stats?

Something like:

```
singularity exec --bind /fs1/ /fs1/resources/containers/sentieon_202112.sif 
    sentieon driver \
        -r "/fs1/resources/ref/hg38/fasta/GCA_000001405.15_GRCh38_no_alt_analysis_set_nochr.fna" \
        -i /fs1/results/wgs/bam/<sample id goes here>_mito.bam \
        --algo CoverageMetrics \
        --cov_thresh 500  \
        mito_cov_metrix.txt
```

I tried it and it seems to work.

**Comment by alkc** [comment]
## Task list:

- [ ] Add new process to `main.nf` to calculate mito coverage stats w/ sentieon
- [ ] Parse and merge coverage stats output w/ existing QC json passed to CDM (or as a new param to `register_sample.py`)
- [ ] Confirm that QC.json is generated correctly
- [ ] Test with a live run.
